version: '3.8'
services:
  user-service:
    build: .
    ports:
      - "8072:8072"
    expose:
      - '8072'
    networks:
      - infrastructure
    volumes:
      - type: bind
        source: ./secrets
        target: /secrets
    environment:
      MONGO_DB_URI: mongodb://root:root@localhost:27017/groopy
      DOCKER_DEFAULT_PLATFORM: linux/amd64/v3
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/groopy-auth.json
  mongodb_container:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

networks:
  infrastructure:
    driver: bridge

volumes:
  mongodb_data_container:
