spring:
  config:
    import: file:.env[.properties]
  application.name: user-service
  data:
    mongodb:
      uri: ${MONGO_DB_URI}

firebase:
  api-key: ${FIREBASE_API_KEY}
  host: 'https://identitytoolkit.googleapis.com/v1/'

grpc:
  server:
    port: 8071
    security:
      enabled: false
