spring:
  application.name: user-service

elasticsearch:
  host: localhost
  port: 9200

firebase:
  key: 'AIzaSyDWPGT6TyVUsc4v_3dsa8UrkPc725-ZXgc'
  clientId: '111117984710785484601'
  projectId: 'groopy-9356d'
  authentication:
    host: 'https://identitytoolkit.googleapis.com/v1/'
    signUpEndpoint: 'accounts:signUp'

grpc:
  server:
    port: 8071
    security:
      enabled: false
