server:
  port: 8091
spring:
  application.name: user-service

elasticsearch:
  host: groopy-db.es.us-central1.gcp.cloud.es.io:443
  port: 9200
  username: elastic
  password: W0ETCOArYU2DO5w4yTJSfK8n

firebase:
  key: 'AIzaSyDWPGT6TyVUsc4v_3dsa8UrkPc725-ZXgc'
  authentication:
    host: 'https://identitytoolkit.googleapis.com/v1/'
    signUpEndpoint: 'accounts:signUp'

grpc:
  server:
    port: 8071
    security:
      enabled: true