#server.address=192.168.1.144
server:
  port: 8090
spring:
  application.name: room-service

  kafka:
    bootstrap-servers: kafka:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
#      value-deserializer: app.groopy.userservice.infrastructure.kafka.UserServiceServiceKafkaDeserializer

elasticsearch:
  host: elasticsearch
  port: 9200