server:
  port: 8091
spring:
  application.name: user-service

elasticsearch:
  host: 0.0.0.0
  port: 9200

firebase:
  key: 'AIzaSyDWPGT6TyVUsc4v_3dsa8UrkPc725-ZXgc'
  authentication:
    host: 'https://identitytoolkit.googleapis.com/v1/'
    signUpEndpoint: 'accounts:signUp'

grpc:
  server:
    port: 8071
    security:
      enabled: false