spring:
  application.name: user-service
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PWD}@${MONGO_DB_HOST}/${MONGO_HUB}?retryWrites=true&w=majority

firebase:
  key: ${FIREBASE_API_KEY}
  authentication:
    host: 'https://identitytoolkit.googleapis.com/v1/'

grpc:
  server:
    port: 8071
    security:
      enabled: false
